### ISSUE TITLE
Overzoom feature not working in 0.8.0

### ISSUE THREAD

**Issue by kkieffer** [merlos/MapCache#32]
I just updated my pod spec to 0.8.0 to try out the new over zoom feature but it doesn't seem to be implemented.  Looking at the code I don't see the "CachedTileOverlayZoomRenderer.swift" file in the Pod. Is it possible something didn't make it to the release?

**Comment by merlos** [comment]
I was able to successfully use the 0.8.0 in OpenGpxTracker https://github.com/merlos/iOS-Open-GPX-Tracker/pull/188

The file is `CachedTileOverlayRenderer.swift`, I renamed the class on a later commit to make it shorter. 

For me the file appears in the Pod when installed using pod install.

![image](https://user-images.githubusercontent.com/404446/94600201-8f0bdc80-025f-11eb-94af-750f51aba17d.png)

Did you do a clean in your build?

**Comment by kkieffer** [comment]
Ok I see my issue.  I'm using my own Renderers. It would be helpful if CachedTileOverlayRenderer and CachedTileOverlay were "open" classes so they could be extended, then I'd be able to use.

**Comment by merlos** [comment]
Release 0.8.2 should fix your problem 

It's 0.8.2 because I messed up with 0.8.1 🙈

**Comment by kkieffer** [comment]
Thanks!  It works now!
